### ISSUE TITLE
Clientside stuff declared on serverside?

### ISSUE THREAD

**Issue by Tokeli** [SirLyle/Lanolin#2]
Getting a crash when trying to load the 0.1b on a server!

Here's the crashlog: https://pastebin.com/pmA16J6J

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lanolin (lanolin)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
```

**Comment by SirLyle** [comment]
Fixed, working its way through the curse approvals. Thank you for reporting with a crash log.
