### ISSUE TITLE
Free water resitance

### ISSUE THREAD

**Issue by TimGoll** [SirLyle/Lanolin#4]
When you add one lanolin in the grid and remove it, you get water breathing for free

![image](https://user-images.githubusercontent.com/13639408/46549086-3522e700-c8d1-11e8-99d4-263093afd1ee.png)

**Comment by TimGoll** [comment]
It seems to be fixed with asierkas update. But I will report back in a week or so

**Comment by SirLyle** [comment]
Please do.

**Comment by TimGoll** [comment]
It seems to work and I close it for now. If I get a problem in the future, I'll reopen it
